### ISSUE TITLE
Duplication of builtin vim.tbl_contains()

### ISSUE THREAD

**Issue by CKolkey** [NarutoXY/dim.lua#1]
https://github.com/NarutoXY/dim.lua/blob/2cdca0e3c43dc36ac09d7096794aa6908ca53196/lua/dim.lua#L14

If I'm not mistaken, this is the same as `vim.tbl_contains()`

**Comment by NarutoXY** [comment]
fixed with 6a0af91562cb088bd8067cfcb16f2b5d0e2899be
