### ISSUE TITLE
Should support more "common" languages to be useful

### ISSUE THREAD

**Issue by nyngwang** [NarutoXY/dim.lua#2]
I need these:

    ◍ clangd (c, c++)
    ◍ omnisharp (c#)
    ◍ pylsp (python)

Currently it doesn't work with clangd and pylsp.

**Comment by nyngwang** [comment]
Just confirmed that it doesn't work on clangd.

**Comment by nyngwang** [comment]
Just confirmed that it doesn't work on pylsp.

**Comment by NarutoXY** [comment]
Python Support might be possible with `vulture` and `null-ls.nvim`

Commit: 7a55457

Minimal config:
```lua
use {
  "jose-elias-alvarez/null-ls.nvim",
  after = "nvim-lspconfig",
  config = function()
-- Start null-ls if it's in servers table
require("null-ls").setup({
  debug = true,
  sources = {
    require("null-ls").builtins.diagnostics.vulture,
  },
})  
  end,
}
```

**Comment by nyngwang** [comment]
I still prefer `pylsp` since it provides much faster linter (on-save) and less CPU-intensive (compared to `pyright`). But happy to know that `null-ls` is supported since I once relied on it.

**Comment by marcomayer** [comment]
Nice plugin! Golang support would also be amazing!

**Comment by NarutoXY** [comment]
Someone made https://github.com/zbirenbaum/neodim, It also works with Golang @marcomayer
