### ISSUE TITLE
Bug: Dim out part of the next line if the current dim-out line is removed

### ISSUE THREAD

**Issue by nyngwang** [NarutoXY/dim.lua#3]
To reproduce:

1. Add an unused var. E.g. `local foo` in the following image: <img src="https://user-images.githubusercontent.com/24765272/157538224-0be7c5a4-506c-4712-aec6-b59081b8b13d.png" width="400">
2. Remove the entire line containing the unused var (The `ins` got dimmed out): <img src="https://user-images.githubusercontent.com/24765272/157538100-315c4cea-cc9b-4f15-aefc-40bf591f71d7.png" width="400">

**Comment by NarutoXY** [comment]
Fixed with 5fe5414e7bf12e07224aaaac6b4fb93da3c6ddcf

**Comment by nyngwang** [comment]
Thank you!
