### ISSUE TITLE
The CPU usage is too high

### ISSUE THREAD

**Issue by nyngwang** [NarutoXY/dim.lua#4]
As title. And it seems that even though I provide `change_in_insert = false,`, it is still dimming out text in insert mode.

Without this plugin the CPU usage is always < peak=50% (with LSP enable, browsing one of my lua config <300 lines). When this plugin is enabled the number goes to >75%(when typing long text). And the delay is sensible.

This problem must be taken seriously to really make it useful in real(i.e. large) projects.

**Comment by NarutoXY** [comment]
Thanks for trying out the plugin. I think the issue might be with frequent autocmds on `TextChanged`. I have changed it to only to call `dim.hig_unused()` on `DiagnosticChange` in 47ccaef. Feedback will be appreciated

**Comment by NarutoXY** [comment]
fixed it in 7d8b9c4572f26074f332da1f8cb4c97169738481
