### ISSUE TITLE
Normal usage major bug

### ISSUE THREAD

**Issue by axieax** [NarutoXY/dim.lua#5]
During normal usage, the following errors appear:

![image](https://user-images.githubusercontent.com/62098008/157896974-d3d4ec82-f7ba-4170-8ab4-9dc79db947c8.png)

followed by

![image](https://user-images.githubusercontent.com/62098008/157897268-d948fe2c-fd34-4388-a598-83c466724eda.png)

These errors keep returning so the only way to resolve them is to keep the plugin disabled.

To reproduce this, create a Python file and start typing `def hello(w:`. A similar issue can be seen when deleting the top half of a function.

**Comment by NarutoXY** [comment]
fixed it in 7d8b9c4572f26074f332da1f8cb4c97169738481
